"""
Workspace Socket.IO DTOs

This package contains data transfer objects for Socket.IO communication
between office4ai (Workspace) and Office Add-In clients.

Architecture:
- These DTOs are internal to the Workspace environment
- They define the protocol for Add-In ↔ Workspace communication
- NOT to be confused with office4ai/dtos/ which are for A2C-SMCP protocol
"""

from office4ai.environment.workspace.dtos.common import (
    BaseRequest,
    BaseResponse,
    ErrorCode,
    ErrorResponse,
)

# Excel DTOs (OASP 0.3.0 events-excel.md, milestone #3 — #18 read + #19 Range + #20 Format + #21 Worksheet + #22 Table)
from office4ai.environment.workspace.dtos.excel import (
    ActivateWorksheetData,
    AddTableRowData,
    AddWorksheetData,
    BorderFormat,
    ConditionalFormatRule,
    DeleteTableRowData,
    DeleteWorksheetData,
    ExcelActivateWorksheetRequest,
    ExcelAddConditionalFormatRequest,
    ExcelAddTableRowRequest,
    ExcelAddWorksheetRequest,
    ExcelClearConditionalFormatRequest,
    ExcelClearRangeRequest,
    ExcelCopyRangeRequest,
    ExcelDeleteRangeRequest,
    ExcelDeleteTableRowRequest,
    ExcelDeleteWorksheetRequest,
    ExcelGetRangeFormatRequest,
    ExcelGetRangeRequest,
    ExcelGetSelectedRangeRequest,
    ExcelGetTableRequest,
    ExcelGetTablesRequest,
    ExcelGetWorkbookInfoRequest,
    ExcelGetWorksheetInfoRequest,
    ExcelGetWorksheetsRequest,
    ExcelInsertRangeRequest,
    ExcelInsertTableRequest,
    ExcelMergeCellsRequest,
    ExcelRenameWorksheetRequest,
    ExcelSetFormulaRequest,
    ExcelSetRangeFormatRequest,
    ExcelSetRangeRequest,
    ExcelSortTableRequest,
    ExcelUnmergeCellsRequest,
    GetRangeData,
    GetRangeFormatData,
    GetTableData,
    GetTablesData,
    GetWorksheetsData,
    InsertTableData,
    RangeBorders,
    RangeFillInfo,
    RangeFontInfo,
    RangeFormatInfo,
    RangeOperationResult,
    RenameWorksheetData,
    SelectedRangeInfo,
    SetAlignmentFormat,
    SetFillFormat,
    SetFontFormat,
    SetRangeFormatOptions,
    SheetInfo,
    SortField,
    SortTableData,
    TableColumnInfo,
    TableSummary,
    UsedRangeInfo,
    WorkbookInfo,
    WorksheetInfo,
)

# PPT DTOs
from office4ai.environment.workspace.dtos.ppt import (
    PptDeleteSlideRequest,
    PptGetCurrentSlideElementsRequest,
    PptGetSlideElementsRequest,
    PptGetSlideScreenshotRequest,
    PptInsertImageRequest,
    PptInsertShapeRequest,
    PptInsertTableRequest,
    PptInsertTextRequest,
    PptMoveSlideRequest,
    PptUpdateTextBoxRequest,
)

# Word DTOs
from office4ai.environment.workspace.dtos.word import (
    SelectionInfo,
    SelectTextResult,
    WordAppendTextRequest,
    WordExportContentRequest,
    WordGetDocumentStatsRequest,
    WordGetDocumentStructureRequest,
    WordGetSelectedContentRequest,
    WordGetSelectionRequest,
    WordGetSelectionResponse,
    WordGetVisibleContentRequest,
    WordInsertEquationRequest,
    WordInsertImageRequest,
    WordInsertTableRequest,
    WordInsertTextRequest,
    WordInsertTOCRequest,
    WordReplaceSelectionRequest,
    WordReplaceTextRequest,
    WordSelectTextRequest,
)

__all__ = [
    # Common
    "BaseRequest",
    "BaseResponse",
    "ErrorResponse",
    "ErrorCode",
    # Word
    "WordGetSelectedContentRequest",
    "WordGetSelectionRequest",
    "WordGetSelectionResponse",
    "WordGetVisibleContentRequest",
    "WordGetDocumentStructureRequest",
    "WordGetDocumentStatsRequest",
    "WordInsertTextRequest",
    "WordReplaceSelectionRequest",
    "WordReplaceTextRequest",
    "WordSelectTextRequest",
    "SelectTextResult",
    "WordAppendTextRequest",
    "WordInsertImageRequest",
    "WordInsertTableRequest",
    "WordInsertEquationRequest",
    "WordInsertTOCRequest",
    "WordExportContentRequest",
    "SelectionInfo",
    # Excel read slice (#18)
    "ExcelGetWorkbookInfoRequest",
    "ExcelGetWorksheetInfoRequest",
    "ExcelGetSelectedRangeRequest",
    "SheetInfo",
    "UsedRangeInfo",
    "WorkbookInfo",
    "WorksheetInfo",
    "SelectedRangeInfo",
    # Excel Range CRUD + 公式 (#19)
    "ExcelGetRangeRequest",
    "ExcelSetRangeRequest",
    "ExcelClearRangeRequest",
    "ExcelCopyRangeRequest",
    "ExcelDeleteRangeRequest",
    "ExcelInsertRangeRequest",
    "ExcelSetFormulaRequest",
    "RangeFontInfo",
    "RangeFillInfo",
    "RangeFormatInfo",
    "GetRangeData",
    "RangeOperationResult",
    # Excel Format / 条件格式 / 合并单元格 (#20)
    "ExcelGetRangeFormatRequest",
    "ExcelSetRangeFormatRequest",
    "ExcelAddConditionalFormatRequest",
    "ExcelClearConditionalFormatRequest",
    "ExcelMergeCellsRequest",
    "ExcelUnmergeCellsRequest",
    "GetRangeFormatData",
    "BorderFormat",
    "RangeBorders",
    "SetFontFormat",
    "SetFillFormat",
    "SetAlignmentFormat",
    "SetRangeFormatOptions",
    "ConditionalFormatRule",
    # Excel Worksheet 管理 (#21)
    "ExcelGetWorksheetsRequest",
    "ExcelAddWorksheetRequest",
    "ExcelDeleteWorksheetRequest",
    "ExcelRenameWorksheetRequest",
    "ExcelActivateWorksheetRequest",
    "GetWorksheetsData",
    "AddWorksheetData",
    "DeleteWorksheetData",
    "RenameWorksheetData",
    "ActivateWorksheetData",
    # Excel Table 操作 (#22)
    "ExcelInsertTableRequest",
    "ExcelGetTableRequest",
    "ExcelGetTablesRequest",
    "ExcelAddTableRowRequest",
    "ExcelDeleteTableRowRequest",
    "ExcelSortTableRequest",
    "SortField",
    "TableColumnInfo",
    "TableSummary",
    "InsertTableData",
    "GetTableData",
    "GetTablesData",
    "AddTableRowData",
    "DeleteTableRowData",
    "SortTableData",
    # PPT
    "PptGetCurrentSlideElementsRequest",
    "PptGetSlideElementsRequest",
    "PptGetSlideScreenshotRequest",
    "PptInsertTextRequest",
    "PptInsertImageRequest",
    "PptInsertTableRequest",
    "PptInsertShapeRequest",
    "PptDeleteSlideRequest",
    "PptMoveSlideRequest",
    "PptUpdateTextBoxRequest",
]
